### PR TITLE
Check if Viewport is null

### LINKED ISSUE #6: If the Viewport is null the editor crashes
This happens if for example you set a timer to call a function that uses UETorch every 0.1 seconds and at some point quit the game but a call to the function is still done.

### PR DESCRIPTION
**Pull request by marioyc**
Fixes #6

### CODE REVIEW

File: Source/UETorch/Private/UETorch.cpp [hunk 1]
```diff
@@ -118,6 +118,10 @@ typedef struct {
  */
 extern "C" void GetViewportSize(IntSize* r)
 {
+  if(GEngine->GameViewport->Viewport == NULL){
```
Comment (adamlerer) [inline Source/UETorch/Private/UETorch.cpp]: Are you sure that GEngine->GameViewport is never NULL? Maybe check that as well.

Comment (marioyc) [inline Source/UETorch/Private/UETorch.cpp]: According to [this](https://docs.unrealengine.com/latest/INT/Programming/Slate/InGameUI/index.html), both GEngine and GameViewport can be NULL, I'll the checks for both of them.

**Comment by adamlerer** [comment]
thanks @marioyc !
